package edu.jiabao.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import java.util.List;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TIMING".
*/
public class TimingDao extends AbstractDao<Timing, Integer> {

    public static final String TABLENAME = "TIMING";

    /**
     * Properties of entity Timing.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Timing_id = new Property(0, int.class, "timing_id", true, "TIMING_ID");
        public final static Property Timing_name = new Property(1, String.class, "timing_name", false, "TIMING_NAME");
        public final static Property Timing_type = new Property(2, int.class, "Timing_type", false, "TIMING_TYPE");
        public final static Property Device_id = new Property(3, int.class, "device_id", false, "DEVICE_ID");
        public final static Property Operator_list = new Property(4, String.class, "operator_list", false, "OPERATOR_LIST");
        public final static Property Time = new Property(5, java.util.Date.class, "time", false, "TIME");
    }

    private final StringConverter operator_listConverter = new StringConverter();

    public TimingDao(DaoConfig config) {
        super(config);
    }
    
    public TimingDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TIMING\" (" + //
                "\"TIMING_ID\" INTEGER PRIMARY KEY NOT NULL ," + // 0: timing_id
                "\"TIMING_NAME\" TEXT," + // 1: timing_name
                "\"TIMING_TYPE\" INTEGER NOT NULL ," + // 2: Timing_type
                "\"DEVICE_ID\" INTEGER NOT NULL ," + // 3: device_id
                "\"OPERATOR_LIST\" TEXT," + // 4: operator_list
                "\"TIME\" INTEGER);"); // 5: time
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TIMING\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Timing entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getTiming_id());
 
        String timing_name = entity.getTiming_name();
        if (timing_name != null) {
            stmt.bindString(2, timing_name);
        }
        stmt.bindLong(3, entity.getTiming_type());
        stmt.bindLong(4, entity.getDevice_id());
 
        List operator_list = entity.getOperator_list();
        if (operator_list != null) {
            stmt.bindString(5, operator_listConverter.convertToDatabaseValue(operator_list));
        }
 
        java.util.Date time = entity.getTime();
        if (time != null) {
            stmt.bindLong(6, time.getTime());
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Timing entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getTiming_id());
 
        String timing_name = entity.getTiming_name();
        if (timing_name != null) {
            stmt.bindString(2, timing_name);
        }
        stmt.bindLong(3, entity.getTiming_type());
        stmt.bindLong(4, entity.getDevice_id());
 
        List operator_list = entity.getOperator_list();
        if (operator_list != null) {
            stmt.bindString(5, operator_listConverter.convertToDatabaseValue(operator_list));
        }
 
        java.util.Date time = entity.getTime();
        if (time != null) {
            stmt.bindLong(6, time.getTime());
        }
    }

    @Override
    public Integer readKey(Cursor cursor, int offset) {
        return cursor.getInt(offset + 0);
    }    

    @Override
    public Timing readEntity(Cursor cursor, int offset) {
        Timing entity = new Timing( //
            cursor.getInt(offset + 0), // timing_id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // timing_name
            cursor.getInt(offset + 2), // Timing_type
            cursor.getInt(offset + 3), // device_id
            cursor.isNull(offset + 4) ? null : operator_listConverter.convertToEntityProperty(cursor.getString(offset + 4)), // operator_list
            cursor.isNull(offset + 5) ? null : new java.util.Date(cursor.getLong(offset + 5)) // time
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Timing entity, int offset) {
        entity.setTiming_id(cursor.getInt(offset + 0));
        entity.setTiming_name(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setTiming_type(cursor.getInt(offset + 2));
        entity.setDevice_id(cursor.getInt(offset + 3));
        entity.setOperator_list(cursor.isNull(offset + 4) ? null : operator_listConverter.convertToEntityProperty(cursor.getString(offset + 4)));
        entity.setTime(cursor.isNull(offset + 5) ? null : new java.util.Date(cursor.getLong(offset + 5)));
     }
    
    @Override
    protected final Integer updateKeyAfterInsert(Timing entity, long rowId) {
        return entity.getTiming_id();
    }
    
    @Override
    public Integer getKey(Timing entity) {
        if(entity != null) {
            return entity.getTiming_id();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Timing entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
